import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { Amplify } from 'aws-amplify';
import App from './App';
import './brand.css';

// Generated by `ampx sandbox` at the repo root. Gitignored — it holds
// environment-specific ids, so it is never committed.
import outputs from '../../../amplify_outputs.json';

// No allowGuestAccess here: the console is staff-only and every call uses
// authMode 'userPool'. The public form is the only guest path, and it lives in
// the website repo.
Amplify.configure(outputs);

const container = document.getElementById('root');
if (container === null) throw new Error('#root not found');

createRoot(container).render(
  <StrictMode>
    <App />
  </StrictMode>,
);
